server:
  port: 8004  #表示注册到zookeeper服务器的支付服务提供者端口号

spring:
  application:
    name: springcloud-payment-service  #服务别名--注册到zookeeper中心的名称
  cloud:
    zookeeper:
      connect-string: 139.155.203.191:2181  #zookeeper远程服务器的IP加端口号