server:
  port: 8002

#spring的配置
spring:
  application:
    name: springcloud-consumer-dept  #默认注册进eureka中的实例名称（显示大写）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin

#eureka的配置，确定客户端服务注册到eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-consumer-dept-8002  #修改eureka上默认的服务描述信息
    prefer-ip-address: true  #访问路径可以显示ip地址